version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: TPPE
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quarkus_net

  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
#    build: .
    container_name: quarkus-app
    depends_on:
      - mysql
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/TPPE
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: rootpass
    ports:
      - "8080:8080"
    networks:
      - quarkus_net
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
#    command: ./mvnw quarkus:dev -Dquarkus.http.host=0.0.0.0

volumes:
  mysql_data:

networks:
  quarkus_net:
