sonar.organization=samuel-sato-1
sonar.projectKey=samuel-sato_TPPE

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src

# compiled classes, required for Java analysis without the Maven plugin
sonar.java.binaries=target/classes

# ignore Dockerfiles under src/main/docker (not application source code)
sonar.exclusions=src/main/docker/**