name : Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 24
  JAVA_VERSION: 21

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - run: java --version

      - name: Checkstyle
        working-directory: backend
        run: mvn checkstyle:check

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - run: java --version

      - name: Testes
        working-directory: backend
        run: mvn test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-target
          path: backend/target

      

  SonarQube:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download artifact Compile
        uses: actions/download-artifact@v4
        with:
          name: backend-target
          path: backend/target


      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build:
    environment: development

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    
    - name: Echo
      run: echo "Building the project in ${{ job.environment }} environment"
  
  Build-Production:
    environment: production

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    
    - name: Echo
      run: echo "Building the project in ${{ job.environment }} environment"

  