name : Pipeline

on:
  push:
    branches: [ main, developer ]
  pull_request:
    branches: [ main, developer ]
  workflow_dispatch:

env:
  NODE_VERSION: 24
  JAVA_VERSION: 21

jobs:

  Context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Info
        run: |
          echo "Branch: ${{ github.ref_name}}"
          echo "Actor: ${{ github.actor}}"
          echo "Commit: ${{ github.sha}}"
          echo "Commit message: ${{ github.event.head_commit.message}}"
          echo "Runner Number: ${{ github.run_number}}"

  Lint:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - run: java --version

      - name: Checkstyle
        working-directory: backend
        run: mvn checkstyle:check

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - run: java --version

      - name: Testes
        working-directory: backend
        run: mvn test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-target
          path: backend/target

      

  SonarQube:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download artifact Compile
        uses: actions/download-artifact@v4
        with:
          name: backend-target
          path: backend/target


      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
          scanMetadataReportFile: backend/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     

  Build:
    needs: SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    
    - name: Set up JDK Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        cache: 'maven'


    - name: Download artifact Compile
      uses: actions/download-artifact@v4
      with:
        name: backend-target
        path: backend/target

    - name: Generate package
      working-directory: backend
      run: mvn verify

    
    - name: Echo
      run: echo "Building the project in ${{ vars.ENVIRONMENT }}"

  Deploy-Dev:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref_name == 'developer'
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download artifact Compile
        uses: actions/download-artifact@v4
        with:
          name: backend-target

      - name: Echo
        run: echo "Deploying the project in ${{ vars.ENVIRONMENT }}"
  

  Deploy-Prod:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download artifact Compile
        uses: actions/download-artifact@v4
        with:
          name: backend-target

      - name: Echo
        run: echo "Deploying the project in ${{ vars.ENVIRONMENT }}"