name : Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 24
  JAVA_VERSION: 21

jobs:
  Análise Estática:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up jdk Java
      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ env.JAVA_VERSION }}

      - run: java --version
        